//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBankID.Infrastructure.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccounts
    {
        public int Id_account { get; set; }
        public int Id_user { get; set; }
        public int Id_account_type { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime Date_opened { get; set; }
        public string Currency { get; set; }
        public decimal Interest_rate { get; set; }
        public System.DateTime Closing_date { get; set; }
    
        public virtual AccountTypes AccountTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
