//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBankID.Infrastructure.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id_request { get; set; }
        public int Id_user { get; set; }
        public int Id_request_type { get; set; }
        public System.DateTime Request_date { get; set; }
        public string Request_status { get; set; }
    
        public virtual RequestTypes RequestTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
